from selenium import webdriver
from selenium.webdriver.common.by import By
import time
driver = webdriver.Chrome()
driver.get("https://blinkit.com/")
driver.maximize_window()
time.sleep(5)
location = driver.find_element(By.NAME, "select-locality")
location.click()
location.send_keys("Kalavasal")
time.sleep(3)
kalavasal = driver.find_element(By.XPATH,"//div[contains(@class,'LocationSearchList__LocationLabel') and normalize-space()='Kalavasal']")
kalavasal.click()
time.sleep(5)
snacks = driver.find_element(By.XPATH,"//img[contains(@alt,'Snacks & Munchies')]")
snacks.click()
time.sleep(5)
product = driver.find_element(By.XPATH,"//div[contains(text(),'Bingo Popped Sour Cream')]")
product.click()
time.sleep(5)
add_cart = driver.find_element(By.XPATH,"//div[@role='button' and .//div[normalize-space()='Add to cart']]")
add_cart.click()
time.sleep(5)
cart = driver.find_element(By.XPATH,"//div[contains(@class,'CartButton__Button')]")
cart.click()
time.sleep(8)
quantity = driver.find_element(By.XPATH,"//div[contains(@class,'AddToCart__AddMinusIcon') and text()='5']")
print("Quantity:", quantity.text)